/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RevealedFieldResponse } from '../../models/revealed-field-response';

export interface ExtractedFieldsReveal$Plain$Params {
  documentId: string;
  fieldId: string;
}

export function extractedFieldsReveal$Plain(http: HttpClient, rootUrl: string, params: ExtractedFieldsReveal$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<RevealedFieldResponse>> {
  const rb = new RequestBuilder(rootUrl, extractedFieldsReveal$Plain.PATH, 'post');
  if (params) {
    rb.path('documentId', params.documentId, {});
    rb.path('fieldId', params.fieldId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RevealedFieldResponse>;
    })
  );
}

extractedFieldsReveal$Plain.PATH = '/api/documents/{documentId}/extracted-fields/{fieldId}/reveal';
