/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CaseNoteResponse } from '../../models/case-note-response';
import { SaveCaseNoteRequest } from '../../models/save-case-note-request';

export interface CaseNotesSave$Plain$Params {
  caseId: string;
      body?: SaveCaseNoteRequest
}

export function caseNotesSave$Plain(http: HttpClient, rootUrl: string, params: CaseNotesSave$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CaseNoteResponse>> {
  const rb = new RequestBuilder(rootUrl, caseNotesSave$Plain.PATH, 'put');
  if (params) {
    rb.path('caseId', params.caseId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CaseNoteResponse>;
    })
  );
}

caseNotesSave$Plain.PATH = '/api/cases/{caseId}/case-note';
