/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CaseNoteResponse } from '../../models/case-note-response';

export interface CaseNotesGet$Json$Params {
  caseId: string;
}

export function caseNotesGet$Json(http: HttpClient, rootUrl: string, params: CaseNotesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CaseNoteResponse>> {
  const rb = new RequestBuilder(rootUrl, caseNotesGet$Json.PATH, 'get');
  if (params) {
    rb.path('caseId', params.caseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CaseNoteResponse>;
    })
  );
}

caseNotesGet$Json.PATH = '/api/cases/{caseId}/case-note';
