/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from '../models/document-type';
export interface AiReviewInputFieldResponse {
  confidence?: number | null;
  documentId?: string;
  documentType?: DocumentType;
  fieldName?: string | null;
  fieldValue?: string | null;
  id?: string;
  isMasked?: boolean;
}
