/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CaseNoteResponse {
  basedOnAiReviewVersion?: number | null;
  locked?: boolean;
  source?: string | null;
  text?: string | null;
  updatedAt?: string | null;
  updatedByUserId?: string | null;
}
