/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CaseStatus } from '../models/case-status';
import { FindingSeverity } from '../models/finding-severity';
export interface CaseResponse {
  applicantFullName?: string | null;
  createdAt?: string;
  createdByUserId?: string | null;
  firmId?: string | null;
  id?: string;
  riskScore?: number;
  riskTier?: FindingSeverity;
  rowVersion?: string;
  status?: CaseStatus;
  updatedAt?: string;
}
