/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AiConcern } from '../models/ai-concern';
import { AiRecommendation } from '../models/ai-recommendation';
export interface CreateAiReviewRequest {
  draftCaseNote?: string | null;
  keyConcerns?: Array<AiConcern> | null;
  modelName?: string | null;
  modelVersion?: string | null;
  nextSteps?: Array<string> | null;
  rationale?: string | null;
  recommendation?: AiRecommendation;
  summary?: string | null;
}
