/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type DocumentType = 'GovernmentId' | 'ProofOfAddress' | 'Financial' | 'Other' | 'Application' | 'W9' | 'BeneficialOwnership' | 'FormationDocument';

