/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DocumentType } from './document-type';

/**
 * Each possible value of `DocumentType`
 */
export const DOCUMENT_TYPE: DocumentType[] = [
  'GovernmentId',
  'ProofOfAddress',
  'Financial',
  'Other',
  'Application',
  'W9',
  'BeneficialOwnership',
  'FormationDocument'
];