/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ExtractedFieldResponse {
  confidence?: number | null;
  extractedAt?: string;
  fieldName?: string | null;
  fieldValue?: string | null;
  id?: string;
  isMasked?: boolean;
}
