/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FindingSource } from './finding-source';

/**
 * Each possible value of `FindingSource`
 */
export const FINDING_SOURCE: FindingSource[] = [
  'Ai',
  'Manual',
  'Deterministic'
];