/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DemoResetResponse } from '../../models/demo-reset-response';

export interface DemoReset$Plain$Params {
}

export function demoReset$Plain(http: HttpClient, rootUrl: string, params?: DemoReset$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<DemoResetResponse>> {
  const rb = new RequestBuilder(rootUrl, demoReset$Plain.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DemoResetResponse>;
    })
  );
}

demoReset$Plain.PATH = '/api/demo/reset';
